baseURL = "https://relayed.dk"
title = "Relayed"
author = "Thomas Kokholm"
copyright = "Copyright © 2020, Thomas Kokholm."
paginate = 3
languageCode = "da"
DefaultContentLanguage = "da"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "casper3"

[params]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  github = "https://github.com/thomaskokholm"
  description = "Tech nyheder på Dansk"
  mainSections = ["post"]

[menu]
  [[menu.main]]
    identifier = "om"
    name = "Om"
    url = "/om/"
    weight = 10
  [[menu.main]]
    identifier = "skribent"
    name = "Skribent"
    url = "https://kokholm.org"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

