DefaultContentLanguage = "da"
author = "Thomas Kokholm"
baseURL = "https://relayed.dk"
copyright = "Copyright © 2020, Thomas Kokholm."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "da"
paginate = 3
theme = "casper3"
title = "Relayed"
[[menu.main]]
identifier = "skribent"
name = "Skribent"
parent = "Om"
url = "https://kokholm.org"
weight = 2
[[menu.main]]
identifier = "om"
name = "Om"
url = "/om/"
weight = 1
[params]
description = "Tech nyheder opsumeret på Dansk"
github = "https://github.com/thomaskokholm"
mainSections = ["post"]
twitter = "https://twitter.com/kokholmthomas"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
